Repository faissaloux/pest-plugin-math, pull requests merged in 2024-07, with the labels that each got.

#1 `toBeDivisibleBy()`
  .gitignore
  README.md
  composer.json
  phpunit.xml
  src/Autoload.php
  tests/toBeDivisibleBy.php
Labels: enhancement

#3 `Expectations.php`
  src/Autoload.php
  src/Expectations.php
Labels: refactor

#4 Add not->toBeDivisible() tests
  tests/toBeDivisibleBy.php
Labels: tests

#5 `toBePowerOf()`
  README.md
  src/Expectations.php
  tests/toBePowerOf.php
Labels: enhancement

#6 `toBeEven()`
  README.md
  src/Expectations.php
  tests/toBeEven.php
Labels: enhancement

#7 `toBeOdd()`
  README.md
  src/Expectations.php
  tests/toBeOdd.php
Labels: enhancement

#8 `toBePrime()`
  README.md
  src/Expectations.php
  tests/toBePrime.php
Labels: enhancement

#9 Refactor expectations
  phpstan.neon
  src/Autoload.php
  src/Expectation.php
  src/Expectations.php
Labels: refactor

#10 `toBePositive()`
  README.md
  src/Expectation.php
  tests/toBePositive.php
Labels: enhancement

#11 `toBeNegative()`
  README.md
  src/Expectation.php
  tests/toBeNegative.php
Labels: enhancement

#12 Fix dependencies
  composer.json
  composer.lock
Labels: dependencies

#13 `toBeFloat()`
  README.md
  src/Expectation.php
  tests/toBeFloat.php
Labels: enhancement

#15 `toBeSqrtOf()`
  README.md
  src/Expectation.php
  tests/toBeSqrtOf.php
Labels: enhancement

#17 `toBeFactorialOf()`
  README.md
  src/Expectation.php
  tests/toBeFactorialOf.php
Labels: enhancement

#18 Show tests coverage
  .github/workflows/tests.yml
  README.md
  composer.json
Labels: workflow, CI

#23 add an absolute expectation
  .gitignore
  README.md
  src/Expectation.php
  tests/toBeAbsolute.php
Labels: enhancement
